"""Saving caller-supplied bytes to disk — the one piece of logic every
upload endpoint in this system needs, extracted so it exists in exactly one
hardened place rather than once per feature that accepts a file.

Three things guard every save:

- The name on disk is generated by us (a uuid plus an extension derived from
  the content type). The client's filename is never touched — otherwise a
  filename of "../../etc/passwd" would write exactly there.
- The resolved path is checked to sit inside the upload directory before
  anything is written, catching any traversal the first rule missed.
- Size is capped while streaming, so an oversized upload is refused partway
  rather than after it has filled the disk.

Every upload is hashed as it streams, not by re-reading the file afterwards:
a second pass over a large upload is wasted I/O, and re-reading opens a
window where the bytes hashed are not the bytes written.
"""

import hashlib
import uuid
from dataclasses import dataclass
from datetime import date
from io import BytesIO
from pathlib import Path

from fastapi import HTTPException, UploadFile, status
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from app.config import settings

CHUNK_BYTES = 64 * 1024


@dataclass(frozen=True)
class UploadedFile:
    stored_name: str
    size_bytes: int
    sha256_hex: str


async def save_upload_file(file: UploadFile, allowed_content_types: dict[str, str]) -> UploadedFile:
    """Stream `file` to the upload directory under a generated name.

    `allowed_content_types` maps an accepted MIME type to the extension its
    stored name gets — an allowlist, not a blocklist, so a dangerous type
    cannot slip in simply because nobody thought to ban it. Raises the same
    HTTPExceptions a caller would have raised inline: 415 for a type not in
    the map, 413 over `settings.max_upload_bytes`, 400 for an empty file.
    """
    extension = allowed_content_types.get(file.content_type)
    if extension is None:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=(
                f"Unsupported content type '{file.content_type}'. "
                f"Allowed: {sorted(allowed_content_types)}"
            ),
        )

    upload_dir = Path(settings.upload_dir).resolve()
    upload_dir.mkdir(parents=True, exist_ok=True)

    stored_name = f"{uuid.uuid4().hex}{extension}"
    destination = (upload_dir / stored_name).resolve()
    if destination.parent != upload_dir:
        # Unreachable with a generated uuid name; kept as a backstop so
        # that if the naming above is ever changed, this still refuses to
        # write outside the upload directory.
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid upload path")

    written = 0
    digest = hashlib.sha256()
    try:
        with destination.open("wb") as out:
            while chunk := await file.read(CHUNK_BYTES):
                written += len(chunk)
                if written > settings.max_upload_bytes:
                    raise HTTPException(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        detail=f"File exceeds the {settings.max_upload_bytes} byte limit",
                    )
                digest.update(chunk)
                out.write(chunk)
    except Exception:
        # Never leave a partial file behind: it would appear in the store
        # as a real file that cannot be opened.
        destination.unlink(missing_ok=True)
        raise

    if written == 0:
        # An empty file passes every check above and is never a real
        # upload. Refusing it here beats discovering it later.
        destination.unlink(missing_ok=True)
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Uploaded file is empty")

    return UploadedFile(stored_name=stored_name, size_bytes=written, sha256_hex=digest.hexdigest())


def write_seed_placeholder_pdf(
    stored_name: str, *, case_number: str, doc_type_label: str, doc_date: date
) -> UploadedFile:
    """Write a small, honestly-labelled placeholder PDF for a seeded
    Document row, so "Download" on a demo case returns a real file instead
    of a 404 for a stored_name that was only ever written to the row.

    `stored_name` must be a flat filename with no path separators — same
    rule save_upload_file's generated uuid names already satisfy, and the
    one the download route's own traversal guard (path.parent != upload_dir)
    depends on. Callers pick the name; this does not invent one, because a
    backfill script needs a deterministic name to write the same file
    twice without duplicating it.
    """
    if "/" in stored_name or "\\" in stored_name:
        raise ValueError(f"stored_name must be flat, got {stored_name!r}")

    upload_dir = Path(settings.upload_dir).resolve()
    upload_dir.mkdir(parents=True, exist_ok=True)
    destination = (upload_dir / stored_name).resolve()
    if destination.parent != upload_dir:
        raise ValueError(f"stored_name must resolve inside the upload directory, got {stored_name!r}")

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER, topMargin=1 * inch, bottomMargin=1 * inch)
    ink = colors.HexColor("#1F2A24")
    ink_soft = colors.HexColor("#4A5247")
    title_style = ParagraphStyle("title", fontName="Helvetica-Bold", fontSize=16, textColor=ink, spaceAfter=14)
    body_style = ParagraphStyle("body", fontName="Helvetica", fontSize=11, leading=16, textColor=ink)
    notice_style = ParagraphStyle(
        "notice", fontName="Helvetica-Oblique", fontSize=9.5, leading=14, textColor=ink_soft, spaceBefore=24
    )
    story = [
        Paragraph(doc_type_label, title_style),
        Paragraph(f"Case: {case_number}", body_style),
        Paragraph(f"Date on file: {doc_date.strftime('%d %B %Y')}", body_style),
        Spacer(1, 20),
        Paragraph(
            "This is a synthetic placeholder document generated for this prototype's demonstration "
            "data. It stands in for the real instrument a case of this kind would carry on file and "
            "carries no legal or evidentiary weight.",
            notice_style,
        ),
    ]
    doc.build(story)
    content = buffer.getvalue()

    destination.write_bytes(content)
    return UploadedFile(
        stored_name=stored_name,
        size_bytes=len(content),
        sha256_hex=hashlib.sha256(content).hexdigest(),
    )
