"""Case documents: list, upload, download, and what a stage is still missing.

Upload is the only route that writes caller-supplied bytes to disk, so it
carries the real attack surface. Three things guard it:

- The name on disk is generated by us (a uuid plus an extension derived
  from the content type). The client's filename is stored for display only
  and never touches a path — otherwise a filename of "../../etc/passwd"
  would write exactly there.
- The resolved path is checked to sit inside the upload directory before
  anything is written, catching any traversal the first rule missed.
- Size is capped while streaming, so an oversized upload is refused
  partway rather than after it has filled the disk.

Versioning, added alongside: re-uploading a doc_type that a case already has
SUPERSEDES the previous row rather than sitting beside it as a second,
equally authoritative copy. The old row keeps its bytes on disk and its place
in the trail; only `is_current` changes. Nothing is ever deleted, because a
superseded land record is still evidence of what was on file when a decision
was taken.

Every upload is hashed as it streams. The SHA-256 is tamper-evidence: a
repository holding legal instruments has to be able to answer "is this the
file we recorded", and a size in bytes cannot.

Downloads are audited as well as uploads. For a land record, who READ a
document is usually the more sensitive question, and it was the half that was
missing.
"""

import hashlib
import uuid
from datetime import date
from pathlib import Path

from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile, status
from fastapi.responses import FileResponse
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.config import settings
from app.core.enums import DocType, DocumentVerificationStatus, Role
from app.dependencies import get_current_user, get_db, require_role, scope_cases_to_user
from app.models import Case, Document, RequiredDocument, User
from app.schemas.document import (
    DocumentList,
    DocumentOut,
    DocumentVerifyRequest,
    DocumentVersionHistory,
    MissingDocuments,
)
from app.services import audit

router = APIRouter(prefix="/documents", tags=["documents"])

DOCUMENT_UPLOADERS = (
    Role.ADMIN,
    Role.DISTRICT_OFFICER,
    Role.SLAO,
    Role.FIELD_OFFICER,
    Role.RNR_OFFICER,
)

# Reviewing a document is a narrower act than filing one — a field officer
# uploads a survey report, but does not get to mark their own submission
# verified. Matches CASE_WRITERS: whoever can move a case's stage is who
# this system already trusts to decide a document is in order.
DOCUMENT_VERIFIERS = (Role.ADMIN, Role.DISTRICT_OFFICER, Role.SLAO)

# An allowlist, not a blocklist. Anything not named here is refused, so a
# dangerous type cannot slip in simply because nobody thought to ban it.
ALLOWED_CONTENT_TYPES = {
    "application/pdf": ".pdf",
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/tiff": ".tif",
}
CHUNK_BYTES = 64 * 1024


def _case_or_404(db: Session, user: User, case_id: int) -> Case:
    case = scope_cases_to_user(db.query(Case), user).filter(Case.id == case_id).first()
    if case is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case not found")
    return case


@router.get("", response_model=DocumentList)
def list_documents(
    case_id: int = Query(description="Case whose documents to list"),
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
    include_superseded: bool = Query(
        default=False,
        description="Include earlier versions. Off by default so the list shows what is on file now.",
    ),
):
    """Documents on a case — current versions only, unless asked otherwise.

    Defaulting to current-only matters: once a document can be replaced, a
    list that shows every revision by default turns a three-document case
    into a nine-row list where nothing indicates which copy is operative.
    """
    _case_or_404(db, user, case_id)

    query = db.query(Document).filter(Document.case_id == case_id)
    if not include_superseded:
        query = query.filter(Document.is_current.is_(True))

    rows = query.order_by(Document.uploaded_on.desc(), Document.id.desc()).all()

    superseded = (
        db.query(func.count(Document.id))
        .filter(Document.case_id == case_id, Document.is_current.is_(False))
        .scalar()
        or 0
    )
    return DocumentList(
        items=[DocumentOut.model_validate(d) for d in rows],
        total=len(rows),
        superseded_count=int(superseded),
    )


@router.get("/versions", response_model=DocumentVersionHistory)
def document_versions(
    case_id: int = Query(description="Case to inspect"),
    doc_type: DocType = Query(description="Which document type's history to return"),
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Every version of one document type on one case, newest first.

    The revision chain behind a single row in the list above, so a reviewer
    can see that an award copy was replaced, when, and by whom.
    """
    _case_or_404(db, user, case_id)
    rows = (
        db.query(Document)
        .filter(Document.case_id == case_id, Document.doc_type == doc_type)
        .order_by(Document.version.desc(), Document.id.desc())
        .all()
    )
    return DocumentVersionHistory(
        case_id=case_id,
        doc_type=doc_type,
        versions=[DocumentOut.model_validate(d) for d in rows],
    )


@router.get("/missing", response_model=MissingDocuments)
def missing_documents(
    case_id: int = Query(description="Case to check"),
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """What the case's current stage requires but does not have.

    The same comparison the document_missing alert rule makes, exposed per
    case so the case page can show it without waiting for a rule run.
    """
    case = _case_or_404(db, user, case_id)

    required = [
        doc_type
        for (doc_type,) in db.query(RequiredDocument.doc_type)
        .filter(RequiredDocument.stage == case.stage)
        .all()
    ]
    # Only CURRENT versions satisfy a requirement. Without this filter a
    # superseded copy would keep answering for a document that has since
    # been replaced — or withdrawn.
    present = [
        doc_type
        for (doc_type,) in db.query(Document.doc_type)
        .filter(Document.case_id == case_id, Document.is_current.is_(True))
        .all()
    ]

    return MissingDocuments(
        case_id=case_id,
        stage=case.stage.value,
        required=sorted(set(required), key=lambda d: d.value),
        present=sorted(set(present), key=lambda d: d.value),
        missing=sorted(set(required) - set(present), key=lambda d: d.value),
    )


@router.post("", response_model=DocumentOut, status_code=status.HTTP_201_CREATED)
async def upload_document(
    case_id: int = Form(...),
    doc_type: DocType = Form(...),
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    user: User = Depends(require_role(*DOCUMENT_UPLOADERS)),
):
    _case_or_404(db, user, case_id)

    extension = ALLOWED_CONTENT_TYPES.get(file.content_type)
    if extension is None:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=(
                f"Unsupported content type '{file.content_type}'. "
                f"Allowed: {sorted(ALLOWED_CONTENT_TYPES)}"
            ),
        )

    upload_dir = Path(settings.upload_dir).resolve()
    upload_dir.mkdir(parents=True, exist_ok=True)

    stored_name = f"{uuid.uuid4().hex}{extension}"
    destination = (upload_dir / stored_name).resolve()
    if destination.parent != upload_dir:
        # Unreachable with a generated uuid name; kept as a backstop so
        # that if the naming above is ever changed, this still refuses to
        # write outside the upload directory.
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid upload path")

    written = 0
    # Hashed as it streams, not by re-reading the file afterwards: a second
    # pass over a 10 MB upload is wasted I/O, and re-reading opens a window
    # where the bytes hashed are not the bytes written.
    digest = hashlib.sha256()
    try:
        with destination.open("wb") as out:
            while chunk := await file.read(CHUNK_BYTES):
                written += len(chunk)
                if written > settings.max_upload_bytes:
                    raise HTTPException(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        detail=f"File exceeds the {settings.max_upload_bytes} byte limit",
                    )
                digest.update(chunk)
                out.write(chunk)
    except Exception:
        # Never leave a partial file behind: it would appear in the store
        # as a real document that cannot be opened.
        destination.unlink(missing_ok=True)
        raise

    if written == 0:
        # An empty file passes every check above and is never a real
        # document. Refusing it here beats discovering it at a hearing.
        destination.unlink(missing_ok=True)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail="Uploaded file is empty"
        )

    # Supersede the current version of this doc_type, if there is one. The
    # previous row keeps its bytes and its place in the trail; only its
    # is_current flag changes, so the history stays complete.
    previous = (
        db.query(Document)
        .filter(
            Document.case_id == case_id,
            Document.doc_type == doc_type,
            Document.is_current.is_(True),
        )
        .order_by(Document.version.desc())
        .first()
    )
    next_version = (previous.version + 1) if previous else 1
    if previous is not None:
        previous.is_current = False

    document = Document(
        case_id=case_id,
        doc_type=doc_type,
        # Path(...).name strips any directory part the client sent.
        filename=Path(file.filename or "upload").name[:255],
        stored_name=stored_name,
        content_type=file.content_type,
        size_bytes=written,
        uploaded_by_user_id=user.id,
        uploaded_on=date.today(),
        version=next_version,
        supersedes_id=previous.id if previous else None,
        is_current=True,
        sha256=digest.hexdigest(),
        # A fresh upload is unreviewed even when it replaces a verified
        # one — the previous review was of different bytes, and carrying
        # a VERIFIED status onto a file nobody has looked at would be a
        # false signal to whoever reads the document list next.
        verification_status=DocumentVerificationStatus.PENDING,
    )
    db.add(document)
    db.flush()
    audit.record(
        db,
        user,
        action="document.upload",
        entity_type="document",
        entity_id=document.id,
        detail=(
            f"{doc_type.value} v{next_version} on case {case_id} "
            f"({written} bytes, sha256={document.sha256[:12]}…)"
            + (f" superseding #{previous.id}" if previous else "")
        ),
    )
    db.commit()
    db.refresh(document)
    return DocumentOut.model_validate(document)


@router.get("/{document_id}/download")
def download_document(
    document_id: int,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Stream a document back, after checking the caller may see its case."""
    document = db.get(Document, document_id)
    if document is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    # Entitlement is checked against the case, not the document: knowing a
    # document id must never be enough to read another district's file.
    _case_or_404(db, user, document.case_id)

    upload_dir = Path(settings.upload_dir).resolve()
    path = (upload_dir / document.stored_name).resolve()
    if path.parent != upload_dir or not path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Document file is not on disk"
        )

    # Reads are audited as well as writes. For a land record, who opened a
    # document is usually the more sensitive question, and it was the half
    # the trail was missing.
    audit.record(
        db,
        user,
        action="document.download",
        entity_type="document",
        entity_id=document.id,
        detail=f"{document.doc_type.value} v{document.version} on case {document.case_id}",
    )
    db.commit()

    return FileResponse(path, media_type=document.content_type, filename=document.filename)


@router.post("/{document_id}/verify", response_model=DocumentOut)
def verify_document(
    document_id: int,
    payload: DocumentVerifyRequest,
    db: Session = Depends(get_db),
    user: User = Depends(require_role(*DOCUMENT_VERIFIERS)),
):
    """VERIFY, REJECT, or SEND FOR CORRECTION — anything but a plain
    VERIFIED requires a remark, checked here rather than only on the
    frontend, the same rule every other review action in this system
    enforces server-side."""
    document = db.get(Document, document_id)
    if document is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Document not found")
    _case_or_404(db, user, document.case_id)

    if payload.status != DocumentVerificationStatus.VERIFIED and not (
        payload.note and payload.note.strip()
    ):
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            "A remark is required unless you are marking this document verified.",
        )

    document.verification_status = payload.status
    document.verification_note = payload.note
    document.verified_by_user_id = user.id
    document.verified_on = date.today()

    audit.record(
        db,
        user,
        action="document.verify",
        entity_type="document",
        entity_id=document.id,
        detail=f"{document.doc_type.value} v{document.version} -> {payload.status.value}"
        + (f": {payload.note}" if payload.note else ""),
    )
    db.commit()
    db.refresh(document)
    return DocumentOut.model_validate(document)
