"""Case documents: list, upload, download, and what a stage is still missing.

Upload is the only route that writes caller-supplied bytes to disk, so it
carries the real attack surface. Three things guard it:

- The name on disk is generated by us (a uuid plus an extension derived
  from the content type). The client's filename is stored for display only
  and never touches a path — otherwise a filename of "../../etc/passwd"
  would write exactly there.
- The resolved path is checked to sit inside the upload directory before
  anything is written, catching any traversal the first rule missed.
- Size is capped while streaming, so an oversized upload is refused
  partway rather than after it has filled the disk.
"""

import uuid
from datetime import date
from pathlib import Path

from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile, status
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.config import settings
from app.core.enums import DocType, Role
from app.dependencies import get_current_user, get_db, require_role, scope_cases_to_user
from app.models import Case, Document, RequiredDocument, User
from app.schemas.document import DocumentList, DocumentOut, MissingDocuments
from app.services import audit

router = APIRouter(prefix="/documents", tags=["documents"])

DOCUMENT_UPLOADERS = (
    Role.ADMIN,
    Role.DISTRICT_OFFICER,
    Role.SLAO,
    Role.FIELD_OFFICER,
    Role.RNR_OFFICER,
)

# An allowlist, not a blocklist. Anything not named here is refused, so a
# dangerous type cannot slip in simply because nobody thought to ban it.
ALLOWED_CONTENT_TYPES = {
    "application/pdf": ".pdf",
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/tiff": ".tif",
}
CHUNK_BYTES = 64 * 1024


def _case_or_404(db: Session, user: User, case_id: int) -> Case:
    case = scope_cases_to_user(db.query(Case), user).filter(Case.id == case_id).first()
    if case is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case not found")
    return case


@router.get("", response_model=DocumentList)
def list_documents(
    case_id: int = Query(description="Case whose documents to list"),
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    _case_or_404(db, user, case_id)
    rows = (
        db.query(Document)
        .filter(Document.case_id == case_id)
        .order_by(Document.uploaded_on.desc(), Document.id.desc())
        .all()
    )
    return DocumentList(items=[DocumentOut.model_validate(d) for d in rows], total=len(rows))


@router.get("/missing", response_model=MissingDocuments)
def missing_documents(
    case_id: int = Query(description="Case to check"),
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """What the case's current stage requires but does not have.

    The same comparison the document_missing alert rule makes, exposed per
    case so the case page can show it without waiting for a rule run.
    """
    case = _case_or_404(db, user, case_id)

    required = [
        doc_type
        for (doc_type,) in db.query(RequiredDocument.doc_type)
        .filter(RequiredDocument.stage == case.stage)
        .all()
    ]
    present = [
        doc_type
        for (doc_type,) in db.query(Document.doc_type).filter(Document.case_id == case_id).all()
    ]

    return MissingDocuments(
        case_id=case_id,
        stage=case.stage.value,
        required=sorted(set(required), key=lambda d: d.value),
        present=sorted(set(present), key=lambda d: d.value),
        missing=sorted(set(required) - set(present), key=lambda d: d.value),
    )


@router.post("", response_model=DocumentOut, status_code=status.HTTP_201_CREATED)
async def upload_document(
    case_id: int = Form(...),
    doc_type: DocType = Form(...),
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    user: User = Depends(require_role(*DOCUMENT_UPLOADERS)),
):
    _case_or_404(db, user, case_id)

    extension = ALLOWED_CONTENT_TYPES.get(file.content_type)
    if extension is None:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=(
                f"Unsupported content type '{file.content_type}'. "
                f"Allowed: {sorted(ALLOWED_CONTENT_TYPES)}"
            ),
        )

    upload_dir = Path(settings.upload_dir).resolve()
    upload_dir.mkdir(parents=True, exist_ok=True)

    stored_name = f"{uuid.uuid4().hex}{extension}"
    destination = (upload_dir / stored_name).resolve()
    if destination.parent != upload_dir:
        # Unreachable with a generated uuid name; kept as a backstop so
        # that if the naming above is ever changed, this still refuses to
        # write outside the upload directory.
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid upload path")

    written = 0
    try:
        with destination.open("wb") as out:
            while chunk := await file.read(CHUNK_BYTES):
                written += len(chunk)
                if written > settings.max_upload_bytes:
                    raise HTTPException(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        detail=f"File exceeds the {settings.max_upload_bytes} byte limit",
                    )
                out.write(chunk)
    except Exception:
        # Never leave a partial file behind: it would appear in the store
        # as a real document that cannot be opened.
        destination.unlink(missing_ok=True)
        raise

    document = Document(
        case_id=case_id,
        doc_type=doc_type,
        # Path(...).name strips any directory part the client sent.
        filename=Path(file.filename or "upload").name[:255],
        stored_name=stored_name,
        content_type=file.content_type,
        size_bytes=written,
        uploaded_by_user_id=user.id,
        uploaded_on=date.today(),
    )
    db.add(document)
    db.flush()
    audit.record(
        db,
        user,
        action="document.upload",
        entity_type="document",
        entity_id=document.id,
        detail=f"{doc_type.value} on case {case_id} ({written} bytes)",
    )
    db.commit()
    db.refresh(document)
    return DocumentOut.model_validate(document)


@router.get("/{document_id}/download")
def download_document(
    document_id: int,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Stream a document back, after checking the caller may see its case."""
    document = db.get(Document, document_id)
    if document is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    # Entitlement is checked against the case, not the document: knowing a
    # document id must never be enough to read another district's file.
    _case_or_404(db, user, document.case_id)

    upload_dir = Path(settings.upload_dir).resolve()
    path = (upload_dir / document.stored_name).resolve()
    if path.parent != upload_dir or not path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Document file is not on disk"
        )

    return FileResponse(path, media_type=document.content_type, filename=document.filename)
