"""baseline: the schema as deployed

The schema exactly as `Base.metadata.create_all()` had been building it up
to this point — 24 tables, no changes. Nothing here is new work; it exists
so that from now on every schema change is a revision instead of a model
edit that silently never reaches a running database.

**An existing database must be stamped, not upgraded.** Its tables are
already there, so running this would fail on the first CREATE TABLE:

    alembic stamp 0001 && alembic upgrade head

A fresh database just runs `alembic upgrade head`. DEPLOYMENT.md carries
both paths.

One known difference between a stamped database and a fresh one: the
deployed database also has `idx_parcels_geom`, a duplicate GiST index
GeoAlchemy2 created automatically beside the explicit one. Revision 0002
drops it, which is why stamping at 0001 and then upgrading converges the
two rather than leaving the older database subtly different forever.

Revision ID: 0001
Revises: 
Create Date: 2026-09-04 15:28:44.166539+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # noqa: F401  emitted by autogenerate
from geoalchemy2 import Geometry  # noqa: F401  emitted by autogenerate
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('required_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('preliminary_notification', 'social_impact_assessment', 'land_verification', 'objection_period', 'declaration', 'award', 'rehabilitation_resettlement', 'possession', 'monitoring', name='stage'), nullable=False),
    sa.Column('doc_type', sa.Enum('notification_copy', 'gazette_publication', 'sia_report', 'public_hearing_minutes', 'land_record', 'survey_map', 'ownership_proof', 'objection_form', 'hearing_notice', 'declaration_copy', 'award_copy', 'compensation_assessment', 'rnr_entitlement_list', 'rnr_scheme_document', 'possession_certificate', 'monitoring_report', name='doc_type'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage', 'doc_type', name='uq_required_documents_stage_doc')
    )
    op.create_index(op.f('ix_required_documents_stage'), 'required_documents', ['stage'], unique=False)
    op.create_table('stage_sla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('preliminary_notification', 'social_impact_assessment', 'land_verification', 'objection_period', 'declaration', 'award', 'rehabilitation_resettlement', 'possession', 'monitoring', name='stage'), nullable=False),
    sa.Column('standard_days', sa.Integer(), nullable=False),
    sa.Column('statutory_days', sa.Integer(), nullable=True),
    sa.Column('warn_at_fraction', sa.Float(), nullable=False),
    sa.Column('basis', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('lgd_code', sa.String(length=10), nullable=True),
    sa.Column('is_union_territory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_states_lgd_code'), 'states', ['lgd_code'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('lgd_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_districts_lgd_code'), 'districts', ['lgd_code'], unique=False)
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('requiring_body', sa.String(length=120), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_district_id'), 'projects', ['district_id'], unique=False)
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('lgd_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villages_district_id'), 'villages', ['district_id'], unique=False)
    op.create_index(op.f('ix_villages_lgd_code'), 'villages', ['lgd_code'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('preliminary_notification', 'social_impact_assessment', 'land_verification', 'objection_period', 'declaration', 'award', 'rehabilitation_resettlement', 'possession', 'monitoring', name='stage'), nullable=False),
    sa.Column('status', sa.Enum('active', 'stalled', 'closed', name='case_status'), nullable=False),
    sa.Column('stage_changed_at', sa.Date(), nullable=False),
    sa.Column('stage_due_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_district_id'), 'cases', ['district_id'], unique=False)
    op.create_index(op.f('ix_cases_project_id'), 'cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_cases_stage'), 'cases', ['stage'], unique=False)
    op.create_index(op.f('ix_cases_stage_due_on'), 'cases', ['stage_due_on'], unique=False)
    op.create_index(op.f('ix_cases_village_id'), 'cases', ['village_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('has_land_title', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_village_id'), 'people', ['village_id'], unique=False)
    op.create_table('affected_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('is_landowner', sa.Boolean(), nullable=False),
    sa.Column('is_displaced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'person_id', name='uq_affected_family_case_person')
    )
    op.create_index(op.f('ix_affected_families_case_id'), 'affected_families', ['case_id'], unique=False)
    op.create_index(op.f('ix_affected_families_person_id'), 'affected_families', ['person_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity'), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_case_id'), 'alerts', ['case_id'], unique=False)
    op.create_index(op.f('ix_alerts_rule'), 'alerts', ['rule'], unique=False)
    op.create_table('compensation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('amount_awarded', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assessed', 'awarded', 'paid', 'disputed', name='compensation_status'), nullable=False),
    sa.Column('awarded_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensation_case_id'), 'compensation', ['case_id'], unique=False)
    op.create_index(op.f('ix_compensation_person_id'), 'compensation', ['person_id'], unique=False)
    op.create_table('objections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('grounds', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('filed', 'under_review', 'resolved', 'rejected', name='objection_status'), nullable=False),
    sa.Column('filed_on', sa.Date(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objections_case_id'), 'objections', ['case_id'], unique=False)
    op.create_index(op.f('ix_objections_person_id'), 'objections', ['person_id'], unique=False)
    op.create_geospatial_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('survey_number', sa.String(length=20), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('notified', 'under_acquisition', 'acquired', 'possession_taken', name='parcel_status'), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('boundary', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('ix_parcels_boundary', 'parcels', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_parcels_case_id'), 'parcels', ['case_id'], unique=False)
    op.create_geospatial_index('ix_parcels_geom', 'parcels', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_parcels_owner_id'), 'parcels', ['owner_id'], unique=False)
    op.create_index(op.f('ix_parcels_survey_number'), 'parcels', ['survey_number'], unique=False)
    op.create_table('rnr_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'disputed', name='rnr_status'), nullable=False),
    sa.Column('entitlement', sa.String(length=200), nullable=True),
    sa.Column('updated_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rnr_records_case_id'), 'rnr_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_rnr_records_person_id'), 'rnr_records', ['person_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('landowner', 'field_officer', 'slao', 'rnr_officer', 'district_officer', 'requiring_body', 'state_officer', 'ministry_officer', 'admin', name='role'), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('organisation', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('case_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.Enum('preliminary_notification', 'social_impact_assessment', 'land_verification', 'objection_period', 'declaration', 'award', 'rehabilitation_resettlement', 'possession', 'monitoring', name='stage'), nullable=True),
    sa.Column('to_stage', sa.Enum('preliminary_notification', 'social_impact_assessment', 'land_verification', 'objection_period', 'declaration', 'award', 'rehabilitation_resettlement', 'possession', 'monitoring', name='stage'), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_stage_history_case_id'), 'case_stage_history', ['case_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('notification_copy', 'gazette_publication', 'sia_report', 'public_hearing_minutes', 'land_record', 'survey_map', 'ownership_proof', 'objection_form', 'hearing_notice', 'declaration_copy', 'award_copy', 'compensation_assessment', 'rnr_entitlement_list', 'rnr_scheme_document', 'possession_certificate', 'monitoring_report', name='doc_type'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_on', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_is_current'), 'documents', ['is_current'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_supersedes_id'), 'documents', ['supersedes_id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selector', sa.String(length=16), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('landowner', 'field_officer', 'slao', 'rnr_officer', 'district_officer', 'requiring_body', 'state_officer', 'ministry_officer', 'admin', name='role'), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('organisation', sa.String(length=120), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_selector'), 'invite_codes', ['selector'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('rule', sa.String(length=60), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_case_id'), 'notifications', ['case_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_rule'), 'notifications', ['rule'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('uq_notification_open_per_user_case_rule', 'notifications', ['user_id', 'case_id', 'rule'], unique=True, postgresql_where=sa.text('is_read IS false'))
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_number', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('requiring_body', sa.String(length=120), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('estimated_area_ha', sa.Float(), nullable=False),
    sa.Column('estimated_families', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_scrutiny', 'returned', 'approved', 'rejected', 'withdrawn', name='proposal_status'), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_on', sa.Date(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('status_changed_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_case_id'), 'proposals', ['case_id'], unique=False)
    op.create_index(op.f('ix_proposals_district_id'), 'proposals', ['district_id'], unique=False)
    op.create_index(op.f('ix_proposals_proposal_number'), 'proposals', ['proposal_number'], unique=True)
    op.create_index(op.f('ix_proposals_state_id'), 'proposals', ['state_id'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_index(op.f('ix_proposals_submitted_by_user_id'), 'proposals', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_proposals_village_id'), 'proposals', ['village_id'], unique=False)
    op.create_table('proposal_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('draft', 'submitted', 'under_scrutiny', 'returned', 'approved', 'rejected', 'withdrawn', name='proposal_status'), nullable=True),
    sa.Column('to_status', sa.Enum('draft', 'submitted', 'under_scrutiny', 'returned', 'approved', 'rejected', 'withdrawn', name='proposal_status'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.Enum('landowner', 'field_officer', 'slao', 'rnr_officer', 'district_officer', 'requiring_body', 'state_officer', 'ministry_officer', 'admin', name='role'), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_reviews_proposal_id'), 'proposal_reviews', ['proposal_id'], unique=False)
    op.create_table('statutory_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('notice_type', sa.Enum('preliminary_notification', 'declaration', 'award', 'possession_notice', name='notice_type'), nullable=False),
    sa.Column('section_reference', sa.String(length=40), nullable=False),
    sa.Column('gazette_number', sa.String(length=60), nullable=True),
    sa.Column('issuing_authority', sa.String(length=160), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=True),
    sa.Column('beneficiary_count', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'notice_type', name='uq_statutory_notice_case_type')
    )
    op.create_index(op.f('ix_statutory_notices_case_id'), 'statutory_notices', ['case_id'], unique=False)
    op.create_index(op.f('ix_statutory_notices_issued_on'), 'statutory_notices', ['issued_on'], unique=False)
    op.create_index(op.f('ix_statutory_notices_notice_type'), 'statutory_notices', ['notice_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statutory_notices_notice_type'), table_name='statutory_notices')
    op.drop_index(op.f('ix_statutory_notices_issued_on'), table_name='statutory_notices')
    op.drop_index(op.f('ix_statutory_notices_case_id'), table_name='statutory_notices')
    op.drop_table('statutory_notices')
    op.drop_index(op.f('ix_proposal_reviews_proposal_id'), table_name='proposal_reviews')
    op.drop_table('proposal_reviews')
    op.drop_index(op.f('ix_proposals_village_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_submitted_by_user_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_state_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_proposal_number'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_district_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_case_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('uq_notification_open_per_user_case_rule', table_name='notifications', postgresql_where=sa.text('is_read IS false'))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_rule'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_case_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_invite_codes_selector'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_documents_supersedes_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_current'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_case_stage_history_case_id'), table_name='case_stage_history')
    op.drop_table('case_stage_history')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rnr_records_person_id'), table_name='rnr_records')
    op.drop_index(op.f('ix_rnr_records_case_id'), table_name='rnr_records')
    op.drop_table('rnr_records')
    op.drop_index(op.f('ix_parcels_survey_number'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_owner_id'), table_name='parcels')
    op.drop_geospatial_index('ix_parcels_geom', table_name='parcels', postgresql_using='gist', column_name='geom')
    op.drop_index(op.f('ix_parcels_case_id'), table_name='parcels')
    op.drop_geospatial_index('ix_parcels_boundary', table_name='parcels', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('parcels')
    op.drop_index(op.f('ix_objections_person_id'), table_name='objections')
    op.drop_index(op.f('ix_objections_case_id'), table_name='objections')
    op.drop_table('objections')
    op.drop_index(op.f('ix_compensation_person_id'), table_name='compensation')
    op.drop_index(op.f('ix_compensation_case_id'), table_name='compensation')
    op.drop_table('compensation')
    op.drop_index(op.f('ix_alerts_rule'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_case_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_affected_families_person_id'), table_name='affected_families')
    op.drop_index(op.f('ix_affected_families_case_id'), table_name='affected_families')
    op.drop_table('affected_families')
    op.drop_index(op.f('ix_people_village_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_cases_village_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_stage_due_on'), table_name='cases')
    op.drop_index(op.f('ix_cases_stage'), table_name='cases')
    op.drop_index(op.f('ix_cases_project_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_district_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_villages_lgd_code'), table_name='villages')
    op.drop_index(op.f('ix_villages_district_id'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_projects_district_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_lgd_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_states_lgd_code'), table_name='states')
    op.drop_table('states')
    op.drop_table('stage_sla')
    op.drop_index(op.f('ix_required_documents_stage'), table_name='required_documents')
    op.drop_table('required_documents')
    # ### end Alembic commands ###
